services:
  - type: web
    name: smart-tracker
    env: python
    region: india
    plan: free
    buildCommand: pip install -r requirements.txt && python manage.py collectstatic --noinput
    startCommand: gunicorn smart_tracker.wsgi:application
