services:
  - type: web
    name: smart-expense-tracker
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn smart_tracker.wsgi --bind 0.0.0.0:$PORT
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: smart_tracker.settings
